import requests
import json
import os
import base64
import time
from datetime import datetime

# Configuration
COMMON_HEADER = {
    'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:149.0) Gecko/20100101 Firefox/149.0',
    'Accept': '*/*',
    'Accept-Language': 'en-US,en;q=0.9',
    'Referer': 'https://webtv.nettv.com.np/',
    'Origin': 'https://webtv.nettv.com.np',
}

class NetTvScraper:
    def __init__(self, token_json=None):
        self.token_json = token_json
        self.access_token = None
        self.jwt_data = None
        if token_json:
            self.load_token(token_json)

    def load_token(self, token_json):
        data = json.loads(token_json)
        self.access_token = data.get('access_token')
        if self.access_token:
            # Decode JWT to get subscriber info
            payload = self.access_token.split('.')[1]
            # Add padding if necessary
            payload += '=' * (4 - len(payload) % 4)
            self.jwt_data = json.loads(base64.b64decode(payload).decode('utf-8'))

    def get_wms_auth(self):
        if not self.access_token:
            return None
        headers = {**COMMON_HEADER, 'Authorization': f'Bearer {self.access_token}'}
        try:
            res = requests.get('https://ott-resources.geniustv.geniussystems.com.np/nimble/wmsauthsign', headers=headers)
            return res.json().get('wmsauthsign')
        except:
            return None

    def fetch_channels(self):
        if not self.jwt_data:
            return None
        
        reseller_id = self.jwt_data['params']['reseller_id']
        subscriber_id = self.jwt_data['sub']
        serial = self.jwt_data['params']['serial']
        
        url = f"https://ott-livetv-resources.geniustv.geniussystems.com.np/subscriber/livetv/v1/namespaces/{reseller_id}/subscribers/{subscriber_id}/serial/{serial}"
        headers = {**COMMON_HEADER, 'Authorization': f'Bearer {self.access_token}'}
        
        try:
            res = requests.get(url, headers=headers)
            return res.json()
        except:
            return None

    def generate_m3u(self):
        data = self.fetch_channels()
        if not data or 'result' not in data:
            return None
        
        wms_sign = self.get_wms_auth()
        result = data['result']
        categories = {c['id']: c['category'] for c in result['categories']}
        channel_map = result['category_channel_map']
        channels = result['channels']
        
        m3u_content = "#EXTM3U x-tvg-url=\"https://raw.githubusercontent.com/DIWASXD/Net-Tv-Iptv-Playlist/main/webtv.xml.gz\"\n"
        m3u_content += f"# Generated by Net TV Scraper | Dev: @DIWASXD | Date: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}\n\n"
        
        for ch in channels:
            ch_id = ch['id']
            # Find categories for this channel
            ch_cats = [categories.get(m['category_id'], 'Uncategorized') for m in channel_map if m['channel_id'] == ch_id]
            group_title = ch_cats[0] if ch_cats else "General"
            
            logo = ch.get('logo', '')
            name = ch.get('name', 'Unknown')
            
            # Construct stream URL
            if ch.get('channel_urls'):
                orig_url = ch['channel_urls'][0]['path']
                # Net TV links usually require wmsAuthSign
                stream_url = f"{orig_url}"
                if wms_sign:
                    if '?' in stream_url:
                        stream_url += f"&wmsAuthSign={wms_sign}"
                    else:
                        stream_url += f"?wmsAuthSign={wms_sign}"
                
                m3u_content += f'#EXTINF:-1 tvg-id="{ch_id}" tvg-logo="{logo}" group-title="{group_title}", {name}\n'
                m3u_content += f'#KODIPROP:inputstream=inputstream.adaptive\n'
                m3u_content += f'#KODIPROP:inputstream.adaptive.manifest_type=hls\n'
                m3u_content += f'#KODIPROP:http-origin=https://webtv.nettv.com.np\n'
                m3u_content += f'#KODIPROP:http-referrer=https://webtv.nettv.com.np/\n'
                m3u_content += f'#KODIPROP:http-User-Agent={COMMON_HEADER["User-Agent"]}\n'
                m3u_content += f"{stream_url}\n\n"
                
        return m3u_content

def main():
    # Priority 1: Environment Variable (GitHub Secrets)
    token = os.environ.get('NETTV_TOKEN')
    
    # Priority 2: Local nettv.json file
    if not token and os.path.exists('nettv.json'):
        try:
            with open('nettv.json', 'r') as f:
                data = json.load(f)
                token = json.dumps(data)
                print("Using token from nettv.json")
        except Exception as e:
            print(f"Error reading nettv.json: {e}")

    if not token:
        print("Error: No token found in environment variable or nettv.json")
        return

    scraper = NetTvScraper(token)
    m3u = scraper.generate_m3u()
    
    if m3u:
        with open('playlist.m3u', 'w', encoding='utf-8') as f:
            f.write(m3u)
        print("Playlist generated successfully!")
    else:
        print("Failed to generate playlist.")

if __name__ == "__main__":
    main()
